// <auto-generated />
using InredningOnline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InredningOnline.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201226113407_InitialMigrationTest1")]
    partial class InitialMigrationTest1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("InredningOnline.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            Details = "N/A",
                            Name = "Material1",
                            Price = 45m,
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1,
                            Details = "N/A",
                            Name = "Material2",
                            Price = 98m,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            Details = "N/A",
                            Name = "Material3",
                            Price = 67000m,
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2,
                            Details = "N/A",
                            Name = "Material4",
                            Price = 77m,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 10,
                            Details = "N/A",
                            Name = "Material5",
                            Price = 105m,
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1,
                            Details = "N/A",
                            Name = "Material6",
                            Price = 12m,
                            ProjectId = 2
                        });
                });

            modelBuilder.Entity("InredningOnline.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Project4",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("InredningOnline.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "me@nandan.com",
                            IsAdmin = true,
                            Name = "Nandan"
                        },
                        new
                        {
                            Id = 2,
                            Email = "me@hadis.com",
                            IsAdmin = false,
                            Name = "Hadis"
                        },
                        new
                        {
                            Id = 3,
                            Email = "me@ali.com",
                            IsAdmin = false,
                            Name = "Ali"
                        });
                });

            modelBuilder.Entity("InredningOnline.Models.Material", b =>
                {
                    b.HasOne("InredningOnline.Models.Project", null)
                        .WithMany("Materials")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InredningOnline.Models.Project", b =>
                {
                    b.HasOne("InredningOnline.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InredningOnline.Models.Project", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
